### ISSUE TITLE
Update to Directx 12

### ISSUE THREAD

**Issue by gmgj** [mstrange86/milkdrop2_mmport#2]
The learning curve for me to take this and update it to Directx 12 is rather mind boggling.  I just ordered a new machine and I can dedicate the old  to testing.  I suggested on the MediaMonkey forums that they fund this.  But anyway.  Far superior to Milkdrop, Wife goes, that is beautiful.  Thank you for doing it.  If you find yourself wanting to update this to Directx12, I will test whatever you want.

**Comment by mstrange86** [comment]
Hi @gmgj, I think it's probably fine to leave it targeting the legacy version of DirectX, Microsoft generally bends over backwards to keep support for old versions of their libraries around on Windows.

Anyone who wants to port it to a newer version certainly can but there won't really be any value in doing so as 99% of the core DirectX commands are the same. If someone truly wanted to write a newer version of the Milkdrop it would probably be best to come up with a new version of the visualization API that supported general GPU computation (Milkdrop was written in the early days of vertex/pixel shaders) and backport all the existing visualizations to it.
